apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-lab-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-lab
  template:
    metadata:
      labels:
        app: guestbook-lab
    spec:
      containers:
       - name: guestbook-lab
         image: milydemendoza/guestbook-lab:1.0.1
         ports:
         - containerPort: 8082
           name: http
