apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  #- persistent-volume-claim.yaml

commonLabels:
  app: mily-guestbook-lab

namePrefix: mily-guestbook-lab-