apiVersion: v1
kind: Service
metadata:
  name: mily-guestbook-lab-service
spec:
  selector:
    app: mily-guestbook-lab
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8082
  type: ClusterIP