name: cicd

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: milydemendoza/argocd-demo-app
  IMAGE_TAG: "1.0.1"
  GIT_USER_EMAIL: "milydemendoza@gmail.com"
  GIT_USER_NAME: "milydemoreno"

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: milydemendoza/.*|image: milydemendoza/guestbook-lab:${{ env.IMAGE_TAG }}|g" manifest/deployment.yaml

      - name: Push updated manifest to repo
        run: |
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git remote set-url origin "https://x-access-token:${{ secrets.TOKEN }}@github.com/milymoreno/argoPipelineActions.git"
          git add manifest/deployment.yaml
          git diff --quiet || git commit -m "Update to version ${{ env.IMAGE_TAG }}"
          git push origin main
